# Generated by Django 2.2.3 on 2019-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190716_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='referenceurl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
