# Generated by Django 2.2.3 on 2019-10-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_answer_referenceurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='referenceurl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
